version: "3.9"

services:
  gemini-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-server
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env
